version: '3.4'

volumes:
    pgmaster: {}
    pgslave1: {}
    pgslave2: {}
    pgslave3: {}
    pgslave4: {}
    backup: {}
secrets:
   postgres.user.postgres:
     file: postgres.user.postgres.txt
   postgres.user.replication:
     file: postgres.user.replication.txt


services:
    pgmaster:
        image: kt71020/postgres:latest-postgres96
        environment:
            # PARTNER_NODES: "pgmaster,pgslave1,pgslave3"
            PARTNER_NODES: "pgmaster.host,pgslave1.host,pgslave3.host"
            NODE_ID: 1 # Integer number of node
            NODE_NAME: node1 # Node name
            CLUSTER_NODE_NETWORK_NAME: pgmaster.host # (default: hostname of the node)
            NODE_PRIORITY: 100  # (default: 100)
            SSH_ENABLE: 1
            #database we want to use for application
            # POSTGRES_PASSWORD: b1uxcdq
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres.user.postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: monkey_db
            CLEAN_OVER_REWIND: 0
            CONFIGS: "listen_addresses:'*',max_replication_slots:5"
                                  # in format variable1:value1[,variable2:value2[,...]]
                                  # used for pgpool.conf file
            #defaults:
            CLUSTER_NAME: pg_cluster # default is pg_cluster
            REPLICATION_DB: replication_db # default is replication_db
            REPLICATION_USER: replication_user # default is replication_user
            # REPLICATION_PASSWORD: b1uxcdq # default is replication_pass  
            REPLICATION_PASSWORD_FILE: /run/secrets/postgres.user.replication
            TZ: Asia/Taipei
        secrets:
            - postgres.user.postgres
            - postgres.user.replication
        ports:
            - 5432:5432
        volumes:
            - pgmaster:/var/lib/postgresql/data
        deploy:
            mode: replicated
            replicas: 1
            placement:
              constraints:
                - node.labels.mongo.role == Data3
        extra_hosts:
            - "pgmaster.host:10.130.48.90"
            - "pgslave1.host:10.130.45.224"
            - "pgslave2.host:10.130.45.51"
            - "pgslave3.host:10.130.26.240"
            - "pgslave4.host:10.130.14.121"
#<<< Branch 1
    pgslave1:
        image: kt71020/postgres:latest-postgres96
        environment:
            # PARTNER_NODES: "pgmaster,pgslave1,pgslave3"
            PARTNER_NODES: "pgmaster.host,pgslave1.host,pgslave3.host"
            REPLICATION_PRIMARY_HOST: pgmaster.host
            NODE_ID: 2
            NODE_NAME: node2
            CLUSTER_NODE_NETWORK_NAME: pgslave1.host # (default: hostname of the node)
            CLEAN_OVER_REWIND: 1
            CONFIGS: "max_replication_slots:10" #some overrides
            REPLICATION_PASSWORD_FILE: /run/secrets/postgres.user.replication
            TZ: Asia/Taipei
        secrets:
            - postgres.user.replication
        ports:
            - 5441:5432
        volumes:
            - pgslave1:/var/lib/postgresql/data
        depends_on:
            - pgmaster
        deploy:
            mode: replicated
            replicas: 1
            placement:
              constraints:
                - node.labels.mongo.role == cfg1
        extra_hosts:
            - "pgmaster.host:10.130.48.90"
            - "pgslave1.host:10.130.45.224"
            - "pgslave2.host:10.130.45.51"
            - "pgslave3.host:10.130.26.240"
            - "pgslave4.host:10.130.14.121"

    # Add more slaves if required ccccc    
    pgslave2:
        image: kt71020/postgres:latest-postgres96
        environment:
            REPLICATION_PRIMARY_HOST: pgslave1.host # I want to have cascade Streeming replication
            NODE_ID: 3
            NODE_NAME: node3
            CLUSTER_NODE_NETWORK_NAME: pgslave2.host # (default: hostname of the node)
            #USE_REPLICATION_SLOTS: 0
            REPLICATION_PASSWORD_FILE: /run/secrets/postgres.user.replication
            TZ: Asia/Taipei
        secrets:
            - postgres.user.replication
        volumes:
            - pgslave2:/var/lib/postgresql/data        
        ports:
            - 5442:5432 
        depends_on:
            - pgslave1
        deploy:
              mode: replicated
              replicas: 1
              placement:
                constraints:
                  - node.labels.mongo.role == cfg2
        extra_hosts:
            - "pgmaster.host:10.130.48.90"
            - "pgslave1.host:10.130.45.224"
            - "pgslave2.host:10.130.45.51"
            - "pgslave3.host:10.130.26.240"
            - "pgslave4.host:10.130.14.121"
 
#>>> Branch 1
#<<< Branch 2
    pgslave3:
        image: kt71020/postgres:latest-postgres96
        environment:
            # PARTNER_NODES: "pgmaster,pgslave1,pgslave3"
            PARTNER_NODES: "pgmaster.host,pgslave1.host,pgslave3.host"
            REPLICATION_PRIMARY_HOST: pgmaster.host
            NODE_ID: 4
            NODE_NAME: node4
            CLUSTER_NODE_NETWORK_NAME: pgslave3.host # (default: hostname of the node)
            NODE_PRIORITY: 200  # (default: 100)
            CLEAN_OVER_REWIND: 1 
            REPLICATION_PASSWORD_FILE: /run/secrets/postgres.user.replication
            TZ: Asia/Taipei
        secrets:
            - postgres.user.replication
        volumes:
            - pgslave3:/var/lib/postgresql/data
        ports:
            - 5443:5432
        depends_on:
            - pgmaster
        deploy:
              mode: replicated
              replicas: 1
              placement:
                constraints:
                  - node.labels.mongo.role == cfg3
        extra_hosts:
            - "pgmaster.host:10.130.48.90"
            - "pgslave1.host:10.130.45.224"
            - "pgslave2.host:10.130.45.51"
            - "pgslave3.host:10.130.26.240"
            - "pgslave4.host:10.130.14.121"
 

    pgslave4:
        image: kt71020/postgres:latest-postgres96
        environment:
            REPLICATION_PRIMARY_HOST: pgslave3.host
            NODE_ID: 5
            NODE_NAME: node5
            CLUSTER_NODE_NETWORK_NAME: pgslave4.host # (default: hostname of the node)
            #USE_REPLICATION_SLOTS: 0  
            REPLICATION_PASSWORD_FILE: /run/secrets/postgres.user.replication
            TZ: Asia/Taipei
        secrets:
            - postgres.user.replication
        ports:
            - 5444:5432
        depends_on:
            - pgslave3
        volumes:
            - pgslave4:/var/lib/postgresql/data
        deploy:
              mode: replicated
              replicas: 1
              placement:
                constraints:
                  - node.labels.mongo.role == Data1
        extra_hosts:
            - "pgmaster.host:10.130.48.90"
            - "pgslave1.host:10.130.45.224"
            - "pgslave2.host:10.130.45.51"
            - "pgslave3.host:10.130.26.240"
            - "pgslave4.host:10.130.14.121"
#>>> Branch 2
    backup:
        image: kt71020/barman:latest-barman2
        environment:
            REPLICATION_USER: replication_user # default is replication_user
            REPLICATION_PASSWORD: b1uxcdq # default is replication_pass
            # REPLICATION_PASSWORD_FILE: /run/secrets/postgres.user.replication
            REPLICATION_HOST: pgmaster.host
            POSTGRES_PASSWORD: b1uxcdq
            # POSTGRES_PASSWORD_FILE: /run/secrets/postgres.user.postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: monkey_db
            SSH_ENABLE: 1
            BACKUP_SCHEDULE: "*/30 */5 * * *"
            TZ: Asia/Taipei
        volumes:
            - backup:/var/backups
        depends_on:
            - pgmaster
            - pgslave1
            - pgslave3
        deploy:
              mode: replicated
              replicas: 1
              placement:
                constraints:
                  - node.labels.mongo.role == Data2 
        extra_hosts:
            - "pgmaster.host:10.130.48.90"
            - "pgslave1.host:10.130.45.224"
            - "pgslave2.host:10.130.45.51"
            - "pgslave3.host:10.130.26.240"
            - "pgslave4.host:10.130.14.121"
        secrets:
            - postgres.user.postgres
            - postgres.user.replication 
 
    pgpool:
        image: kt71020/pgpool:latest-pgpool36
        environment:
            PCP_USER: postgres
            PCP_PASSWORD: b1uxcdq
            WAIT_BACKEND_TIMEOUT: 60
            CHECK_USER: postgres
            CHECK_PASSWORD: b1uxcdq
            CHECK_PGCONNECT_TIMEOUT: 3 #timout for checking if primary node is healthy
            SSH_ENABLE: 1
            DB_USERS: postgres:b1uxcdq,kt:b1uxcdq # in format user:password[,user:password[...]]
            BACKENDS: "0:pgmaster.host:5432:1:/var/lib/postgresql/data:ALLOW_TO_FAILOVER,1:pgslave1.host::::,3:pgslave3.host::::,2:pgslave2.host::::" #,4:pgslaveDOES_NOT_EXIST::::
                      # in format num:host:port:weight:data_directory:flag[,...]
                      # defaults:
                      #   port: 5432
                      #   weight: 1
                      #   data_directory: /var/lib/postgresql/data
                      #   flag: ALLOW_TO_FAILOVER
            REQUIRE_MIN_BACKENDS: 3 # minimal number of backends to start pgpool (some might be unreachable)
            CONFIGS: "num_init_children:250,max_pool:4"
                      # in format variable1:value1[,variable2:value2[,...]]
                      # used for pgpool.conf file
            TZ: Asia/Taipei
        ports:
            - 5430:5432
            - 9898:9898 # PCP
        depends_on:
            - pgmaster
            - pgslave1
            - pgslave3
        deploy:
              mode: replicated
              replicas: 1
              placement:
                constraints:
                  - node.labels.mongo.role == mongos1
        extra_hosts:
            - "pgmaster.host:10.130.48.90"
            - "pgslave1.host:10.130.45.224"
            - "pgslave2.host:10.130.45.51"
            - "pgslave3.host:10.130.26.240"
            - "pgslave4.host:10.130.14.121"
     
