version: '3.1'
networks:
  postgres:
    driver: overlay
volumes:
    pgmaster: {}
    backup: {}
services:
    pgmaster:
        image: kt71020/postgres:latest-postgres96
        networks:
            - postgres
        environment:
            PARTNER_NODES: "pgmaster,pgslave1,pgslave3"
            NODE_ID: 1 # Integer number of node
            NODE_NAME: node1 # Node name
            CLUSTER_NODE_NETWORK_NAME: pgmaster # (default: hostname of the node)
            NODE_PRIORITY: 100  # (default: 100)
            SSH_ENABLE: 1
            #database we want to use for application
            POSTGRES_PASSWORD: postgres_password
            POSTGRES_USER: postgres
            POSTGRES_DB: monkey_db
            CLEAN_OVER_REWIND: 0
            CONFIGS: "listen_addresses:'*',max_replication_slots:5"
                                  # in format variable1:value1[,variable2:value2[,...]]
                                  # used for pgpool.conf file
            #defaults:
            CLUSTER_NAME: pg_cluster # default is pg_cluster
            REPLICATION_DB: replication_db # default is replication_db
            REPLICATION_USER: replication_user # default is replication_user
            REPLICATION_PASSWORD: postgres_password # default is replication_pass  
            TZ: Asia/Taipei
        ports:
            - "127.0.0.1:5440:5432"
        volumes:
            - pgmaster:/var/lib/postgresql/data
        deploy:
            placement:
              constraints:
                - node.hostname == prod-mongodata-3
#<<< Branch 1
    pgslave1:
        image: kt71020/postgres:latest-postgres96
        networks:
            - postgres
        environment:
            PARTNER_NODES: "pgmaster,pgslave1,pgslave3"
            REPLICATION_PRIMARY_HOST: pgmaster
            NODE_ID: 2
            NODE_NAME: node2
            CLUSTER_NODE_NETWORK_NAME: pgslave1 # (default: hostname of the node)
            CLEAN_OVER_REWIND: 1
            CONFIGS: "max_replication_slots:10" #some overrides
            REPLICATION_PASSWORD: postgres_password # default is replication_pass
            TZ: Asia/Taipei
        ports:
            - "127.0.0.1:5441:5432"
        deploy:
            placement:
              constraints:
                - node.hostname == prod-mongocfg-1

    # Add more slaves if required ccccc    
    pgslave2:
        image: kt71020/postgres:latest-postgres96
        networks:
            - postgres
        environment:
            REPLICATION_PRIMARY_HOST: pgslave1 # I want to have cascade Streeming replication
            NODE_ID: 3
            NODE_NAME: node3
            CLUSTER_NODE_NETWORK_NAME: pgslave2 # (default: hostname of the node)
            #USE_REPLICATION_SLOTS: 0
            REPLICATION_PASSWORD: postgres_password # default is replication_pass
            TZ: Asia/Taipei      
        ports:
            - "127.0.0.1:5442:5432" 
        deploy:
              placement:
                constraints:
                  - node.hostname == prod-mongocfg-2

 
#>>> Branch 1
#<<< Branch 2
    pgslave3:
        image: kt71020/postgres:latest-postgres96
        networks:
            - postgres
        environment:
            PARTNER_NODES: "pgmaster,pgslave1,pgslave3"
            REPLICATION_PRIMARY_HOST: pgmaster
            NODE_ID: 4
            NODE_NAME: node4
            CLUSTER_NODE_NETWORK_NAME: pgslave3 # (default: hostname of the node)
            NODE_PRIORITY: 200  # (default: 100)
            CLEAN_OVER_REWIND: 1 
            REPLICATION_PASSWORD: postgres_password # default is replication_pass
            TZ: Asia/Taipei
        ports:
            - "127.0.0.1:5443:5432"
        deploy:
              placement:
                constraints:
                  - node.hostname == prod-mongocfg-3
    pgslave4:
        image: kt71020/postgres:latest-postgres96
        networks:
            - postgres
        environment:
            REPLICATION_PRIMARY_HOST: pgslave3
            NODE_ID: 5
            NODE_NAME: node5
            CLUSTER_NODE_NETWORK_NAME: pgslave4 # (default: hostname of the node)
            #USE_REPLICATION_SLOTS: 0
            REPLICATION_PASSWORD: postgres_password # default is replication_pass  
            TZ: Asia/Taipei
        ports:
            - "127.0.0.1:5444:5432"
        deploy:
              placement:
                constraints:
                  - node.hostname == prod-mongodata-1

#>>> Branch 2
    backup:
        image: kt71020/barman:latest-barman2
        networks:
            - postgres
        environment:
            REPLICATION_USER: replication_user # default is replication_user
            REPLICATION_PASSWORD: postgres_password # default is replication_pass
            # REPLICATION_PASSWORD_FILE: /run/secrets/postgres.user.replication
            REPLICATION_HOST: pgmaster.host
            POSTGRES_PASSWORD: postgres_password
            POSTGRES_USER: postgres
            POSTGRES_DB: monkey_db
            SSH_ENABLE: 1
            BACKUP_SCHEDULE: "*/30 */5 * * *"
            TZ: Asia/Taipei
        volumes:
            - backup:/var/backups
        deploy:
              placement:
                constraints:
                  - node.hostname == prod-mongodata-2 
 
    pgpool:
        image: kt71020/pgpool:latest-pgpool36
        networks:
            - postgres
        environment:
            PCP_USER: postgres
            PCP_PASSWORD: postgres_password
            WAIT_BACKEND_TIMEOUT: 60
            CHECK_USER: postgres
            CHECK_PASSWORD: postgres_password
            CHECK_PGCONNECT_TIMEOUT: 3 #timout for checking if primary node is healthy
            SSH_ENABLE: 1
            DB_USERS: postgres:postgres_password # in format user:password[,user:password[...]]
            BACKENDS: "0:pgmaster::1:/var/lib/postgresql/data:ALLOW_TO_FAILOVER,1:pgslave1::::,3:pgslave3::::,2:pgslave2::::,4:pgslave2::::" #,4:pgslaveDOES_NOT_EXIST::::
                      # in format num:host:port:weight:data_directory:flag[,...]
                      # defaults:
                      #   port: 5432
                      #   weight: 1
                      #   data_directory: /var/lib/postgresql/data
                      #   flag: ALLOW_TO_FAILOVER
            REQUIRE_MIN_BACKENDS: 3 # minimal number of backends to start pgpool (some might be unreachable)
            CONFIGS: "num_init_children:250,max_pool:5"
                      # in format variable1:value1[,variable2:value2[,...]]
                      # used for pgpool.conf file
            TZ: Asia/Taipei
        ports:
            - 5432:5432
            - 9898:9898 # PCP
        deploy:
              placement:
                constraints:
                  - node.hostname == prod-mongos-1

